#
#  Author: Hari Sekhon
#  Date: 2020-08-22 17:44:47 +0100 (Sat, 22 Aug 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   T r a e f i k   K u s t o m i z a t i o n
# ============================================================================ #

# https://github.com/traefik/traefik-helm-chart

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik  # XXX: 4 objects without explicit namespace as shown by kustomize_check_objects_namespaces.sh in the adjacent DevOps Bash tools repo

resources:
  - namespace.yaml
  - traefik-dashboard-service.yaml
  - traefik-dashboard-basic-auth.yaml
  - traefik-dashboard-add-prefix.yaml
  - traefik-middleware-redirect-https.yaml
  #- traefik-dashboard-external-secret.yaml
  # =======
  # either:
  - traefik-dashboard-ingress.yaml
  - traefik-dashboard-api-ingress.yaml
  # =======
  # or use more advanced ingressroute and cert-manager generated cert due to lack of integration
  - traefik-dashboard-cert.yaml
  - traefik-dashboard-ingressroute.yaml
  - traefik-dashboard-ingressroute-http-redirect.yaml
  # =======
  # XXX: for quickly testing Traefik
  #- whoami.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 22.1.0
    releaseName: traefik
    namespace: traefik
    includeCRDs: true
    valuesFile: values.yaml
