#
#  Author: Hari Sekhon
#  Date: 2021-11-27 11:09:02 +0000 (Sat, 27 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#               T i m e s c a l e D B   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timescaledb  # 11 objects without namespace otherwise

resources:
  - namespace.yaml

helmCharts:
  - name: timescaledb-single
    repo: https://charts.timescale.com
    version: 0.8.2
    releaseName: timescaledb
    namespace: timescaledb
    includeCRDs: true
    valuesFile: values.yaml
