#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2020-09-17 18:18:38 +0100 (Thu, 17 Sep 2020)
#
#  https://github.com/harisekhon/kubernetes-templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  http://www.linkedin.com/in/harisekhon
#

# https://docs.travis-ci.com/user/customizing-the-build/

version: ~> 1.0

# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: bash

# https://docs.travis-ci.com/user/multi-os/
os:
  - linux

# https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
#branches:
#  only:
#    - master

# https://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://docs.travis-ci.com/user/job-lifecycle/

#before_cache:
#  - test -f pytools_checks/Makefile || rm -fr pytools_checks

cache:
  - directories:
    - .cache          # yamllint disable-line rule:indentation
    - pytools_checks  # yamllint disable-line rule:indentation

env:
  - PYTHONUNBUFFERED=1

# avoid package checksum mismatches when installing packages
before_install:
  - sudo rm -f "${TRAVIS_ROOT}/etc/apt/apt.conf.d/99-travis-apt-proxy"
  - sudo rm -rf "${TRAVIS_ROOT}/var/lib/apt/lists/"*

install:
  - travis_retry curl -L git.io/bash-bootstrap | sh

script:
  - travis_retry cd bash-tools && ./check_pytools.sh
