#
#  Author: Hari Sekhon
#  Date: 2021-12-14 16:24:08 +0000 (Tue, 14 Dec 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#               C i r c l e C I   R u n n e r   C o n f i g m a p
# ============================================================================ #

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: circleci-runner
  namespace: circleci
data:
  #resource-class: <namespace>/<resource>
  resource-class: harisekhon/k8s-runner
