#
#  Author: Hari Sekhon
#  Date: 2022-12-09 22:51:25 +0000 (Fri, 09 Dec 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#         E x t e r n a l   S e c r e t s   -   C h a r t   V a l u e s
# ============================================================================ #

# helm repo add external-secrets https://charts.external-secrets.io
#
# helm show values external-secrets/external-secrets >> external-secrets-values.yaml

---
replicaCount: 1

#image:
#  repository: ghcr.io/external-secrets/external-secrets
#  pullPolicy: IfNotPresent
#  # -- The image tag to use. The default is the chart appVersion.
#  # There are different image flavours available, like distroless and ubi.
#  # Please see GitHub release notes for image tags for these flavors.
#  # By default the distroless image is used.
#  tag: ""

installCRDs: true

crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: true
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- If true, external-secrets will perform leader election between instances to ensure no more
# than one instance of external-secrets operates at a time.
leaderElect: false

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: true
  # -- Annotations to add to the service account.
  # XXX: TODO: put GKE Workload Identity / AWS IRSA integration annotations here
  annotations: {}
  # -- Extra Labels to add to the service account.
  extraLabels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""
