#
#  Author: Hari Sekhon
#  Date: 2023-04-14 19:04:01 +0100 (Fri, 14 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                       H A P r o x y   C o n f i g M a p
# ============================================================================ #

# Deprecated: moved to haproxy-values.yaml now

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy
data:
  cr-global: NAMESPACE/NAME   # from haproxy-global.yaml
  cr-defaults: NAMESPACE/NAME # from haproxy-defaults.yaml
  cr-backend: NAMESPACE/NAME  # from haproxy-backend.yaml
