#
#  Author: Hari Sekhon
#  Date: 2021-10-28 16:19:18 +0100 (Thu, 28 Oct 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#            M e t r i c s   S e r v e r   K u s t o m i z a t i o n
# ============================================================================ #

# Metrics Server for EKS - necessary for HPA/VPA use
#
# If deploying on Docker Desktop for a test environment, use metrics-server-docker-kustomization.yaml instead

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#
#   https://artifacthub.io/packages/helm/metrics-server/metrics-server
#
#   version=3.7.0
#   if ! helm repo list | grep -q "^metrics-server[[:space:]]"; then helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/; fi
#   helm template metrics-server -n kube-system metrics-server/metrics-server --version "$version" > metrics-server.yaml
#
- metrics-server.yaml
