#
#  Author: Hari Sekhon
#  Date: 2021-06-09 11:35:22 +0100 (Wed, 09 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# XXX: Danger - this breaks all existing normal ingress terminated SSL services

# This switch was supposedly needed for ArgoCD ingress according to the docs but I've gotten it working without this so don't apply this patch to your nginx ingress controller

- op: add
  path: /spec/template/spec/containers/0/args/1
  value: --enable-ssl-passthrough
