#
#  Author: Hari Sekhon
#  Date: 2021-11-26 17:39:52 +0000 (Fri, 26 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                       V P A   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

# dynamic latest:
#resources:
  #- github.com/kubernetes/autoscaler/vertical-pod-autoscaler/deploy

# stable copy (commit to vcs):
#
#   # uncomment base, comment resources then run this to merge the entire remote kustomization directory:
#
#     kustomize build > vertical-pod-autoscaler-deployment.yaml

# stable versioned copy (commit to vcs) - quite different so above one is currently used:
#
#   helm_template.sh https://charts.fairwinds.com/stable fairwinds-stable/vpa -n kube-system --version 0.5.0 > vertical-pod-autoscaler-deployment.yaml
#
#resources:
#  - vertical-pod-autoscaler-deployment.yaml

helmCharts:
  - name: vpa
    repo: https://charts.fairwinds.com/stable
    #version: 0.5.0
    version: 1.6.1
    releaseName: vpa
    namespace: kube-system
    includeCRDs: true
    #valuesFile: vpa-values.yaml
