#
#  Author: Hari Sekhon
#  Date: 2022-08-10 15:21:14 +0100 (Wed, 10 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 S o n a r Q u b e   K u s t o m i z a t i o n
# ============================================================================ #

# https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes/

# https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube

# initial login is admin/admin - which is forced to change immediately

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonarqube  # XXX: without this ends up in the current namespace due to missing namespace field in 12/16 objects, as shown by kustomize_check_objects_namespaces.sh in the adjacent DevOps Bash tools repo

resources:
  - namespace.yaml

helmCharts:
  - name: sonarqube
    repo: https://SonarSource.github.io/helm-chart-sonarqube
    version: 10.0.0+521
    releaseName: sonarqube
    namespace: sonarqube
    includeCRDs: true
    valuesFile: values.yaml
