#
#  Author: Hari Sekhon
#  Date: 2023-05-12 04:13:43 +0100 (Fri, 12 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                     C l a i r   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: clair

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

helmCharts:
  # old - and breaks in Kustomize with this error:
  #
  #
  #   Error: map[string]interface {}(nil): yaml: unmarshal errors:
  #     line 18: mapping key "name" already defined at line 14
  #     line 23: mapping key "name" already defined at line 19
  #
  #- name: clair
  #  repo: https://wiremind.github.io/wiremind-helm-charts
  #  version: 0.2.9
  #  releaseName: clair
  #  namespace: clair
  #  includeCRDs: true
  #  valuesFile: values.yaml

  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.5.2
    releaseName: clair
    namespace: clair
    includeCRDs: true
    valuesFile: postgres-values.yaml
