#
#  Author: Hari Sekhon
#  Date: 2023-05-16 18:32:37 +0100 (Tue, 16 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                           C l a i r   S e r v i c e
# ============================================================================ #

---
apiVersion: v1
kind: Service
metadata:
  name: clair
  namespace: clair
  labels:
    app.kubernetes.io/instance: clair
    app.kubernetes.io/name: clair
spec:
  type: ClusterIP   # default
  selector:
    app.kubernetes.io/instance: clair
    app.kubernetes.io/name: clair
  ports:
    - name: clair-api
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: clair-health
      port: 8089
      targetPort: 8089
      protocol: TCP
