#
#  Author: Hari Sekhon
#  Date: 2023-05-06 03:13:08 +0100 (Sat, 06 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                  M e t a l   L B   K u s t o m i z a t i o n
# ============================================================================ #

# https://metallb.universe.tf/

# https://metallb.universe.tf/installation/#installation-with-helm

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# XXX: careful this might send prometheus resources to the wrong namespace
namespace: metallb  # 22 objects not namespaced

resources:
  - namespace.yaml
  - metal-lb-ip-address-pool.yaml
  - metal-lb-l2-advertisement.yaml
  - priorityclass.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.13.9
    releaseName: metallb
    namespace: metallb
    includeCRDs: true
    valuesFile: values.yaml
