#
#  Author: Hari Sekhon
#  Date: 2023-05-12 15:43:05 +0100 (Fri, 12 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#            T r i v y   O p e r a t o r   K u s t o m i z a t i o n
# ============================================================================ #

# https://aquasecurity.github.io/trivy-operator/v0.13.2/

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-operator

resources:
  - namespace.yaml

helmCharts:
  - name: trivy-operator
    repo: https://aquasecurity.github.io/helm-charts/
    version: 0.13.2
    releaseName: trivy-operator
    namespace: trivy-operator
    includeCRDs: true
    valuesFile: values.yaml
