#
#  Author: Hari Sekhon
#  Date: 2022-08-05 01:08:09 +0100 (Fri, 05 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          Octopus Deploy Kustomization
# ============================================================================ #

# https://octopus.com/docs/installation/octopus-server-linux-container/octopus-in-kubernetes

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: octopus-deploy

# XXX: need to add secrets:
#
#   octopus-deploy-admin-password  # used by main sts
#   octopus-deploy-sa-password     # used by main sts + mssql deployment
#
# Now added to octopus-deploy-secrets.yaml for convenience of more automation so you don't have to run these each bootstrap
#
# kubectl create secret generic -n octopus-deploy octopus-deploy-admin-password --from-literal=password='0ct@pu55!'
# kubectl create secret generic -n octopus-deploy octopus-deploy-sa-password    --from-literal=password='0ct@pu55!'

resources:
  - namespace.yaml

  # XXX: for production, replace this with one of the better mechanisms documented in secret.yaml
  - octopus-deploy-secrets.yaml

  - octopus-deploy-sts.yaml
  - octopus-deploy-mssql.yaml

  - octopus-deploy-mssql-service.yaml
  # exposes port 80
  - octopus-deploy-web-service.yaml
  # needs full license
  #- octopus-deploy-ha1-service.yaml
  #- octopus-deploy-ha2-service.yaml

  - octopus-deploy-pvc.yaml
  - octopus-deploy-mssql-pvc.yaml

  # enable depending on which cloud you're on
  #- octopus-deploy-aks-pvc.yaml
  #- octopus-deploy-aks-single-pvc.yaml  # alternatively use a single vol
  #
  #- octopus-deploy-gke-filestore-storageclass.yaml
  #- octopus-deploy-gke-pvc.yaml


# doesn't work, has dependency on an outdated chart:
#
#   https://github.com/OctopusSamples/OctopusHelmChart/issues/11
#
#   https://github.com/helm/charts/tree/master/stable/mssql-linux
#
#helmCharts:
#  - name: octopusdeploy
#    repo: https://octopus-helm-charts.s3.amazonaws.com
#    # helm search repo octopus
#    version: 0.1.36
#    releaseName: octopusdeploy
#    namespace: octopus-deploy
#    includeCRDs: true
#    valuesFile: values.yaml
