#
#  Author: Hari Sekhon
#  Date: 2023-04-29 19:09:37 +0100 (Sat, 29 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#               T r a e f i k   H u b   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# XXX: must match traefik proxy namespace
#namespace: traefik

resources:
  - ../base
