#
#  Author: Hari Sekhon
#  Date: 2021-05-19 13:23:05 +0100 (Wed, 19 May 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 Selenium Grid Fully Distributed Kustomization
# ============================================================================ #

# Ties all Selenium Grid Full Distributed resources together for an easy one-shot deployment

# For simpler hub mode, see instead:
#
#   selenium-grid-kustomization.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selenium

resources:
  - priorityclass.yaml
  - namespace.yaml
  # Master Components
  # XXX: Edit ingress address before uncommenting
  #- selenium-grid-router-ingress.yaml
  - selenium-grid-router.yaml
  - selenium-grid-distributor.yaml
  - selenium-grid-event-bus.yaml
  - selenium-grid-sessions.yaml
  - selenium-grid-session-queue.yaml
  # Master Services
  - selenium-grid-router-service.yaml
  - selenium-grid-distributor-service.yaml
  - selenium-grid-event-bus-service.yaml
  - selenium-grid-sessions-service.yaml
  - selenium-grid-session-queue-service.yaml
  # Nodes
  - selenium-grid-node-chrome.yaml
  - selenium-grid-node-firefox.yaml
  - selenium-grid-node-edge.yaml
  # Nodes HPA
  - selenium-grid-node-chrome-hpa.yaml
  - selenium-grid-node-firefox-hpa.yaml
  - selenium-grid-node-edge-hpa.yaml

# done in namespace now
#patchesStrategicMerge:
#  - goldilocks-namespace-enable.patch.yaml

  #- path: ./selenium-grid-node-distributed.patch.yaml
  #  target:
  #    kind: Deployment
  #    labelSelector: app=selenium-node
