#
#  Author: Hari Sekhon
#  Date: 2023-04-13 22:05:38 +0100 (Thu, 13 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   H A P r o x y   K u s t o m i z a t i o n
# ============================================================================ #

# https://www.haproxy.com/documentation/kubernetes/latest/community/install/kubernetes/

# See Also:
#
#   https://github.com/HariSekhon/HAProxy-configs

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: haproxy  # don't enable this, will override echoserver namespace

resources:
  - priorityclass.yaml
  - namespace.yaml
  - haproxy-stats-service.yaml
  - haproxy-stats-ingress.yaml
  #- haproxy-global.yaml
  #- haproxy-defaults.yaml
  #- haproxy-backend.yaml
  #- haproxy-configmap.yaml  # done in haproxy-values.yaml
  # XXX: for quickly testing HAProxy
  #- echoserver.yaml
  #- haproxy-ingress-echoserver.yaml

helmCharts:
  - name: kubernetes-ingress
    repo: https://haproxytech.github.io/helm-charts
    version: 1.29.3
    releaseName: haproxy
    namespace: haproxy
    includeCRDs: true
    valuesFile: values.yaml
