#
#  Author: Hari Sekhon
#  Date: 2023-05-15 00:59:48 +0100 (Mon, 15 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          D o c k e r   S e r v i c e
# ============================================================================ #

---
apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: docker
  labels:
    app: docker-in-docker
spec:
  type: ClusterIP
  selector:
    app: docker-in-docker
  ports:
    - protocol: TCP
      name: http
      port: 2375
      targetPort: 2375
    - protocol: TCP
      name: https
      port: 2376
      targetPort: 2376
