#
#  Author: Hari Sekhon
#  Date: 2023-04-14 21:46:55 +0100 (Fri, 14 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   K y v e r n o   K u s t o m i z a t i o n
# ============================================================================ #

# https://artifacthub.io/packages/helm/kyverno/kyverno

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno  # 1 object (pod) caught unnamespaced

resources:
  - namespace.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 2.7.2
    releaseName: kyverno
    namespace: kyverno
    includeCRDs: true
    valuesFile: values.yaml
