#
#  Author: Hari Sekhon
#  Date: 2021-11-26 09:59:08 +0000 (Fri, 26 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                       E K S   K u s t o m i z a t i o n
# ============================================================================ #

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: kube-system

resources:
  - ../../cluster-autoscaler/base  # XXX: copy environment patches section from cluster-autoscaler to here for base override customizations for specific environment
  - ../../metrics-server/base
  - ../../vpa/base
