#
#  Author: Hari Sekhon
#  Date: 2022-07-28 11:30:56 +0100 (Thu, 28 Jul 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#    B i t n a m i   S e a l e d   S e c r e t s   K u s t o m i z a t i o n
# ============================================================================ #

# https://github.com/bitnami-labs/sealed-secrets

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.5.2
    releaseName: sealed-secrets
    namespace: kube-system                  # kubeseal expects kube-system namespace, otherwise you'd have to use --controller-namespace in every command
    includeCRDs: true
    valuesFile: values.yaml  # overrides name to sealed-secrets-controller as kubeseal expects this, otherwise you'd have to specify --controller-name in every command

# Workaround for:
#
#   https://github.com/bitnami-labs/sealed-secrets/issues/894
#
#   when trying to create a sealed secret from yaml or json output via kubeseal
#
#     error: unable to recognize "sealedsecret.json": no matches for kind "SealedSecret" in version "bitnami.com/v1alpha1"
#   in sealed-secrets controller logs:
#
#     W0728 21:19:14.949824       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: failed to list *v1alpha1.SealedSecret: the server could not find the requested resource (get sealedsecrets.bitnami.com)
#     E0728 21:19:14.949888       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.SealedSecret: failed to list *v1alpha1.SealedSecret: the server could not find the requested resource (get sealedsecrets.bitnami.com)
#
# XXX: superceded via 'includeCRDs: true' in helmCharts section above
#resources:
#  - https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/main/helm/sealed-secrets/crds/sealedsecret-crd.yaml
