#
#  Author: Hari Sekhon
#  Date: 2021-11-26 10:11:42 +0000 (Fri, 26 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    EKS Cluster Autoscaler Deployment Patch
# ============================================================================ #

# Apply:
#
#   run: kubectl patch deploy cluster-autoscaler -n "kube-system" --type json --patch "$(cat eks-cluster-autoscaler-deployment.patch.yaml)"

---
#- op: add
#  path: /spec/template/metadata/annotations/cluster-autoscaler.kubernetes.io~1safe-to-evict  # ~1 is escape for /
#  value: "false"

- op: replace
  path: /spec/template/spec/containers/0/command/3  # XXX: WARNING: must update if the underlying array position changes - limitation of JSON Pointer targeting
  value: --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/<YOUR CLUSTER NAME>  # XXX: Edit cluster name

- op: add
  path: /spec/template/spec/containers/0/command/7  # can't be higher than array index end
  value: --balance-similar-node-groups

- op: add
  path: /spec/template/spec/containers/0/command/8
  value: --skip-nodes-with-system-pods=false

# If using cluster-autoscaler base you may need to override the region
#- op: replace
#  path: /spec/template/spec/containers/0/env/0
#  value:
#    - name: AWS_REGION
#      value: eu-west-2
