#
#  Author: Hari Sekhon
#  Date: 2023-02-08 14:09:31 +0000 (Wed, 08 Feb 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   EKS Node Termination Handler Kustomization
# ============================================================================ #

# https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: kube-system

helmCharts:
  - name: aws-node-termination-handler
    repo: https://aws.github.io/eks-charts/
    version: 0.21.0
    releaseName: aws-node-termination-handler
    namespace: kube-system
    includeCRDs: true
    #valuesFile: values.yaml
