#
#  Author: Hari Sekhon
#  Date: 2021-11-30 18:44:49 +0000 (Tue, 30 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Pluto

on:
  push:
    branches:
      - master
    paths:
      #- '**.y*ml'
      - .github/workflows/pluto.yaml
  pull_request:
    branches:
      - master
    paths:
      - '**.y*ml'
      - .github/workflows/pluto.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

jobs:
  pluto:
    name: Pluto
    uses: HariSekhon/GitHub-Actions/.github/workflows/pluto.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
